import type { CardSchema } from '../types';

// ============================================================
// Custom / HACS Card Schemas
// ============================================================

export const customGenericCardSchema: CardSchema = {
  type: 'custom',
  label: 'Custom Card (Generic)',
  description: 'A generic custom card. Enter the full card type and configure via YAML.',
  icon: 'Puzzle',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'type',
      label: 'Card Type',
      type: 'text',
      required: true,
      helpText: 'Full custom card type (e.g., custom:my-custom-card).',
    },
    {
      name: 'config',
      label: 'Configuration (YAML)',
      type: 'yaml',
      required: true,
      helpText: 'Full card configuration in YAML format.',
    },
  ],
};

export const customButtonCardSchema: CardSchema = {
  type: 'custom:button-card',
  label: 'Button Card (Custom)',
  description: 'Highly customizable button card with templates, CSS styling, and conditional display.',
  icon: 'RectangleHorizontal',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'entity',
      label: 'Entity',
      type: 'entity',
      helpText: 'Entity to bind the button to.',
      isHAStandard: true,
    },
    {
      name: 'name',
      label: 'Name',
      type: 'text',
      helpText: 'Text displayed on the button. Supports templates.',
    },
    {
      name: 'icon',
      label: 'Icon',
      type: 'icon',
      helpText: 'Icon to display (e.g., mdi:lightbulb).',
    },
    {
      name: 'color_type',
      label: 'Color Type',
      type: 'select',
      default: 'icon',
      options: [
        { label: 'Icon', value: 'icon' },
        { label: 'Card', value: 'card' },
        { label: 'Label Card', value: 'label-card' },
        { label: 'Blank Card', value: 'blank-card' },
      ],
      helpText: 'How the color is applied to the button.',
    },
    {
      name: 'color',
      label: 'Color',
      type: 'color',
      default: 'auto',
      helpText: 'Color when the entity is active. Supports auto, rgb, or CSS color.',
    },
    {
      name: 'show_name',
      label: 'Show Name',
      type: 'boolean',
      default: true,
      helpText: 'Display the name text.',
    },
    {
      name: 'show_icon',
      label: 'Show Icon',
      type: 'boolean',
      default: true,
      helpText: 'Display the icon.',
    },
    {
      name: 'show_state',
      label: 'Show State',
      type: 'boolean',
      default: false,
      helpText: 'Display the entity state.',
    },
    {
      name: 'show_label',
      label: 'Show Label',
      type: 'boolean',
      default: false,
      helpText: 'Display the custom label.',
    },
    {
      name: 'label',
      label: 'Label',
      type: 'template',
      helpText: 'Custom label text. Supports Jinja2 templates.',
    },
    {
      name: 'layout',
      label: 'Layout',
      type: 'select',
      default: 'vertical',
      options: [
        { label: 'Vertical', value: 'vertical' },
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Icon Name State', value: 'icon_name_state' },
        { label: 'Name State', value: 'name_state' },
        { label: 'Icon Name', value: 'icon_name' },
        { label: 'Icon State', value: 'icon_state' },
        { label: 'Icon Name State2nd', value: 'icon_name_state2nd' },
        { label: 'Icon State Name2nd', value: 'icon_state_name2nd' },
      ],
      helpText: 'Layout of elements on the button.',
    },
    {
      name: 'size',
      label: 'Icon Size',
      type: 'text',
      default: '40%',
      helpText: 'Size of the icon as a percentage (e.g., 40%).',
    },
    {
      name: 'tap_action',
      label: 'Tap Action',
      type: 'action',
      default: { action: 'toggle' },
      helpText: 'Action performed on tap.',
    },
    {
      name: 'hold_action',
      label: 'Hold Action',
      type: 'action',
      default: { action: 'more-info' },
      helpText: 'Action performed on hold.',
    },
    {
      name: 'styles',
      label: 'CSS Styles (YAML)',
      type: 'yaml',
      helpText: 'Custom CSS styles for card, icon, name, state, label, etc.',
    },
    {
      name: 'state',
      label: 'State Styles (YAML)',
      type: 'yaml',
      helpText: 'Conditional styling based on entity state.',
    },
    {
      name: 'template',
      label: 'Template',
      type: 'text',
      helpText: 'Name of a button-card template to inherit from.',
    },
    {
      name: 'custom_fields',
      label: 'Custom Fields (YAML)',
      type: 'yaml',
      helpText: 'Define custom template areas with HTML/CSS.',
    },
  ],
};

export const customMiniGraphCardSchema: CardSchema = {
  type: 'custom:mini-graph-card',
  label: 'Mini Graph Card',
  description: 'Compact graph card for displaying sensor data with multiple entities and styles.',
  icon: 'TrendingUp',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'entities',
      label: 'Entities',
      type: 'entities-list',
      required: true,
      helpText: 'List of entities to graph. First entity is used for the header.',
      isHAStandard: true,
    },
    {
      name: 'name',
      label: 'Name Override',
      type: 'text',
      helpText: 'Custom card name.',
    },
    {
      name: 'icon',
      label: 'Icon',
      type: 'icon',
      helpText: 'Override the entity icon.',
    },
    {
      name: 'hours_to_show',
      label: 'Hours to Show',
      type: 'number',
      default: 24,
      min: 1,
      helpText: 'Number of hours of history to display.',
    },
    {
      name: 'points_per_hour',
      label: 'Points per Hour',
      type: 'number',
      default: 0.5,
      min: 0.1,
      step: 0.1,
      helpText: 'Number of data points per hour.',
    },
    {
      name: 'line_width',
      label: 'Line Width',
      type: 'number',
      default: 5,
      min: 1,
      max: 20,
      helpText: 'Width of the graph lines.',
    },
    {
      name: 'line_color',
      label: 'Line Color',
      type: 'color',
      helpText: 'Default line color (overridden by per-entity color).',
    },
    {
      name: 'show',
      label: 'Show Options (YAML)',
      type: 'yaml',
      default: { name: true, icon: true, state: true, graph: 'line', fill: true, labels: true, legend: true },
      helpText: 'Toggle visibility of card elements: name, icon, state, graph, fill, labels, legend, etc.',
    },
    {
      name: 'animate',
      label: 'Animate',
      type: 'boolean',
      default: false,
      helpText: 'Animate the graph line drawing on load.',
    },
    {
      name: 'font_size',
      label: 'Font Size',
      type: 'number',
      default: 100,
      min: 50,
      max: 200,
      helpText: 'Font size as a percentage of default.',
    },
    {
      name: 'color_thresholds',
      label: 'Color Thresholds (YAML)',
      type: 'yaml',
      helpText: 'List of value/color pairs to change line color at thresholds.',
    },
  ],
};

export const customApexchartsCardSchema: CardSchema = {
  type: 'custom:apexcharts-card',
  label: 'ApexCharts Card',
  description: 'Advanced charting card powered by ApexCharts. Supports many chart types and data sources.',
  icon: 'AreaChart',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'header',
      label: 'Header (YAML)',
      type: 'yaml',
      helpText: 'Header configuration: show, title, show_states, colorize_states.',
    },
    {
      name: 'graph_span',
      label: 'Graph Span',
      type: 'text',
      default: '24h',
      helpText: 'Time span for the graph (e.g., 24h, 7d, 1m).',
    },
    {
      name: 'span',
      label: 'Span Offset (YAML)',
      type: 'yaml',
      helpText: 'Define a fixed time window: start, end, offset.',
    },
    {
      name: 'series',
      label: 'Data Series (YAML)',
      type: 'yaml',
      required: true,
      helpText:
        'List of data series. Each needs entity and can have: type (line, area, column, scatter), name, color, group_by, etc.',
    },
    {
      name: 'chart_type',
      label: 'Chart Type',
      type: 'select',
      default: 'line',
      options: [
        { label: 'Line', value: 'line' },
        { label: 'Area', value: 'area' },
        { label: 'Scatter', value: 'scatter' },
        { label: 'Pie', value: 'pie' },
        { label: 'Donut', value: 'donut' },
        { label: 'Radial Bar', value: 'radialBar' },
      ],
      helpText: 'Default chart type (can be overridden per series).',
    },
    {
      name: 'update_interval',
      label: 'Update Interval',
      type: 'text',
      helpText: 'How often to refresh data (e.g., 1min, 5min).',
    },
    {
      name: 'all_series_config',
      label: 'All Series Config (YAML)',
      type: 'yaml',
      helpText: 'Default configuration applied to all series.',
    },
    {
      name: 'yaxis',
      label: 'Y-Axis Config (YAML)',
      type: 'yaml',
      helpText: 'Y-axis configuration: min, max, decimals, apex_config.',
    },
    {
      name: 'apex_config',
      label: 'Apex Config (YAML)',
      type: 'yaml',
      helpText: 'Raw ApexCharts configuration object for full customization.',
    },
  ],
};

export const customMushroomEntityCardSchema: CardSchema = {
  type: 'custom:mushroom-entity-card',
  label: 'Mushroom Entity Card',
  description: 'Clean, minimal entity card from the Mushroom card collection.',
  icon: 'CircleDot',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'entity',
      label: 'Entity',
      type: 'entity',
      required: true,
      helpText: 'Entity to display.',
      isHAStandard: true,
    },
    {
      name: 'name',
      label: 'Name Override',
      type: 'text',
      helpText: 'Custom name.',
    },
    {
      name: 'icon',
      label: 'Icon',
      type: 'icon',
      helpText: 'Override the entity icon.',
    },
    {
      name: 'icon_color',
      label: 'Icon Color',
      type: 'color',
      helpText: 'Custom icon color.',
    },
    {
      name: 'layout',
      label: 'Layout',
      type: 'select',
      default: 'default',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
      helpText: 'Card layout style.',
    },
    {
      name: 'fill_container',
      label: 'Fill Container',
      type: 'boolean',
      default: false,
      helpText: 'Fill the height of the parent container.',
    },
    {
      name: 'primary_info',
      label: 'Primary Info',
      type: 'select',
      default: 'name',
      options: [
        { label: 'Name', value: 'name' },
        { label: 'State', value: 'state' },
        { label: 'Last Changed', value: 'last-changed' },
        { label: 'Last Updated', value: 'last-updated' },
        { label: 'None', value: 'none' },
      ],
      helpText: 'What to show as primary info.',
    },
    {
      name: 'secondary_info',
      label: 'Secondary Info',
      type: 'select',
      default: 'state',
      options: [
        { label: 'Name', value: 'name' },
        { label: 'State', value: 'state' },
        { label: 'Last Changed', value: 'last-changed' },
        { label: 'Last Updated', value: 'last-updated' },
        { label: 'None', value: 'none' },
      ],
      helpText: 'What to show as secondary info.',
    },
    {
      name: 'tap_action',
      label: 'Tap Action',
      type: 'action',
      default: { action: 'more-info' },
      helpText: 'Action performed on tap.',
    },
    {
      name: 'hold_action',
      label: 'Hold Action',
      type: 'action',
      helpText: 'Action performed on hold.',
    },
  ],
};

export const customMushroomLightCardSchema: CardSchema = {
  type: 'custom:mushroom-light-card',
  label: 'Mushroom Light Card',
  description: 'Stylish light control card with brightness and color controls from the Mushroom collection.',
  icon: 'Lightbulb',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'entity',
      label: 'Light Entity',
      type: 'entity',
      required: true,
      helpText: 'Light entity to control.',
      isHAStandard: true,
    },
    {
      name: 'name',
      label: 'Name Override',
      type: 'text',
      helpText: 'Custom name.',
    },
    {
      name: 'icon',
      label: 'Icon',
      type: 'icon',
      helpText: 'Override the light icon.',
    },
    {
      name: 'icon_color',
      label: 'Icon Color',
      type: 'color',
      helpText: 'Custom icon color when active.',
    },
    {
      name: 'layout',
      label: 'Layout',
      type: 'select',
      default: 'default',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
      helpText: 'Card layout style.',
    },
    {
      name: 'fill_container',
      label: 'Fill Container',
      type: 'boolean',
      default: false,
      helpText: 'Fill the height of the parent container.',
    },
    {
      name: 'use_light_color',
      label: 'Use Light Color',
      type: 'boolean',
      default: false,
      helpText: 'Colorize the icon using the actual light color.',
    },
    {
      name: 'show_brightness_control',
      label: 'Brightness Control',
      type: 'boolean',
      default: false,
      helpText: 'Show a brightness slider.',
    },
    {
      name: 'show_color_temp_control',
      label: 'Color Temp Control',
      type: 'boolean',
      default: false,
      helpText: 'Show a color temperature slider.',
    },
    {
      name: 'show_color_control',
      label: 'Color Control',
      type: 'boolean',
      default: false,
      helpText: 'Show a color picker.',
    },
    {
      name: 'collapsible_controls',
      label: 'Collapsible Controls',
      type: 'boolean',
      default: false,
      helpText: 'Collapse controls when the light is off.',
    },
    {
      name: 'tap_action',
      label: 'Tap Action',
      type: 'action',
      default: { action: 'toggle' },
      helpText: 'Action performed on tap.',
    },
    {
      name: 'hold_action',
      label: 'Hold Action',
      type: 'action',
      default: { action: 'more-info' },
      helpText: 'Action performed on hold.',
    },
  ],
};

export const customMushroomCoverCardSchema: CardSchema = {
  type: 'custom:mushroom-cover-card',
  label: 'Mushroom Cover Card',
  description: 'Control blinds, shutters, and other cover entities with the Mushroom design language.',
  icon: 'ArrowUpDown',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'entity',
      label: 'Cover Entity',
      type: 'entity',
      required: true,
      helpText: 'Cover entity to control (e.g., cover.living_room_blinds).',
      isHAStandard: true,
    },
    {
      name: 'name',
      label: 'Name Override',
      type: 'text',
      helpText: 'Custom name.',
    },
    {
      name: 'icon',
      label: 'Icon',
      type: 'icon',
      helpText: 'Override the cover icon.',
    },
    {
      name: 'icon_color',
      label: 'Icon Color',
      type: 'color',
      helpText: 'Custom icon color.',
    },
    {
      name: 'layout',
      label: 'Layout',
      type: 'select',
      default: 'default',
      options: [
        { label: 'Default', value: 'default' },
        { label: 'Horizontal', value: 'horizontal' },
        { label: 'Vertical', value: 'vertical' },
      ],
      helpText: 'Card layout style.',
    },
    {
      name: 'show_buttons_control',
      label: 'Show Button Controls',
      type: 'boolean',
      default: false,
      helpText: 'Show open/close/stop buttons.',
    },
    {
      name: 'show_position_control',
      label: 'Show Position Control',
      type: 'boolean',
      default: false,
      helpText: 'Show a position slider.',
    },
    {
      name: 'show_tilt_position_control',
      label: 'Show Tilt Control',
      type: 'boolean',
      default: false,
      helpText: 'Show a tilt position slider.',
    },
    {
      name: 'tap_action',
      label: 'Tap Action',
      type: 'action',
      default: { action: 'toggle' },
      helpText: 'Action performed on tap.',
    },
    {
      name: 'hold_action',
      label: 'Hold Action',
      type: 'action',
      default: { action: 'more-info' },
      helpText: 'Action performed on hold.',
    },
  ],
};

export const customAutoEntitiesCardSchema: CardSchema = {
  type: 'custom:auto-entities',
  label: 'Auto Entities',
  description: 'Automatically populate a card with entities matching filters. Powerful for dynamic dashboards.',
  icon: 'Filter',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'card',
      label: 'Display Card (YAML)',
      type: 'yaml',
      required: true,
      helpText: 'Card type to render the entities in (e.g., entities, glance). Omit the entities field.',
    },
    {
      name: 'filter',
      label: 'Filters (YAML)',
      type: 'yaml',
      required: true,
      helpText:
        'Include/exclude filters. Example:\ninclude:\n  - domain: light\n    state: "on"\nexclude:\n  - entity_id: light.ignored',
    },
    {
      name: 'show_empty',
      label: 'Show When Empty',
      type: 'boolean',
      default: true,
      helpText: 'Show the card even when no entities match.',
    },
    {
      name: 'unique',
      label: 'Unique',
      type: 'boolean',
      default: false,
      helpText: 'Remove duplicate entities from the results.',
    },
    {
      name: 'sort',
      label: 'Sort (YAML)',
      type: 'yaml',
      helpText: 'Sort configuration: method (name, state, entity_id, last_changed), reverse, numeric.',
    },
    {
      name: 'card_param',
      label: 'Card Parameter',
      type: 'text',
      default: 'entities',
      helpText: 'The parameter name in the display card where entities are injected.',
    },
  ],
};

export const customStackInCardSchema: CardSchema = {
  type: 'custom:stack-in-card',
  label: 'Stack in Card',
  description: 'Stack multiple cards inside a single card container, removing individual card borders.',
  icon: 'Layers',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'cards',
      label: 'Cards (YAML)',
      type: 'yaml',
      required: true,
      helpText: 'List of card configurations to stack inside a single card.',
    },
    {
      name: 'mode',
      label: 'Stack Mode',
      type: 'select',
      default: 'vertical',
      options: [
        { label: 'Vertical', value: 'vertical' },
        { label: 'Horizontal', value: 'horizontal' },
      ],
      helpText: 'Direction to stack the cards.',
    },
    {
      name: 'keep',
      label: 'Keep Styles (YAML)',
      type: 'yaml',
      helpText: 'Keep specific card styling: margin, border_radius, background, box_shadow, outer_padding.',
    },
  ],
};

export const customDeclutteringCardSchema: CardSchema = {
  type: 'custom:decluttering-card',
  label: 'Decluttering Card',
  description: 'Reuse card configurations with templates and variables to reduce repetition.',
  icon: 'Copy',
  category: 'custom',
  isCustom: true,
  fields: [
    {
      name: 'template',
      label: 'Template Name',
      type: 'text',
      required: true,
      helpText: 'Name of the decluttering template defined in your Lovelace configuration.',
    },
    {
      name: 'variables',
      label: 'Variables (YAML)',
      type: 'yaml',
      helpText:
        'Variables to pass to the template. Example:\n- entity: light.bedroom\n- name: Bedroom Light',
    },
  ],
};

export const customCardSchemas: CardSchema[] = [
  customGenericCardSchema,
  customButtonCardSchema,
  customMiniGraphCardSchema,
  customApexchartsCardSchema,
  customMushroomEntityCardSchema,
  customMushroomLightCardSchema,
  customMushroomCoverCardSchema,
  customAutoEntitiesCardSchema,
  customStackInCardSchema,
  customDeclutteringCardSchema,
];
